### ISSUE TITLE
Include elf management related functions from libappimage

### ISSUE THREAD

**Issue by azubieta** [linuxdeploy/libelfutil#7]
Migrate functions from this file
https://github.com/AppImage/libappimage/blob/master/src/libappimage_shared/elf.c

**Comment by azubieta** [comment]
This is a sumary of the functions that currently are in the file and wheter they should be:

 - `static uint16_t file16_to_cpu(uint16_t val)` // Dumplicated, already provided by libelf
 - `static uint32_t file32_to_cpu(uint32_t val)`   // Dumplicated, already provided by libelf
 - `static uint64_t file64_to_cpu(uint64_t val)`  // Dumplicated, already provided by libelf
 - `static ssize_t read_elf32(int fd)` // Dumplicated, already provided by libelf
 - `static ssize_t read_elf64(int fd)` // Dumplicated, already provided by libelf
 - `ssize_t appimage_get_elf_size(const char* fname)` // @TheAssassin  mind to comment wich size exactly this should return ?

 - `bool appimage_get_elf_section_offset_and_length(const char* fname, const char* section_name,  unsigned long* offset, unsigned long* length)` // Not shure but libelf should provide something similar

 - `char* read_file_offset_length(const char* fname, unsigned long offset, unsigned long length)` // Not shure but libelf should provide something similar


 - `int appimage_print_hex(char* fname, unsigned long offset, unsigned long length)` // nothing that should be in libelfutil
 - `int appimage_print_binary(char* fname, unsigned long offset, unsigned long length)`  // nothing that should be in libelfutil

**Comment by azubieta** [comment]
As far as I can see there is not too much to migrate here. They should be replaced eventually in the libappimage project by the libelf version.

What do you think?

**Comment by TheAssassin** [comment]
The problem is that libelfutil is C++. We could create a pure C wrapper for libelfutil in the libelfutil project, though, and then use it here, as you said (if we can link libstdc++ statically and publish that on the GitHub release page or so, I don't want to downgrade to C++ < 11 in libelfutil).

**Comment by probonopd** [comment]
We don't want to make libappimage depend on libelf, do we?

**Comment by azubieta** [comment]
@TheAssassin you have a point there, libelfutil is CPP in order to provide the above functions to libappimage we will have to create a C only version.

@probonopd well depending on libelf seems natural to me as an AppImage is an elf file. Also, can be statically linked and is available on Centos 5  see: https://pkgs.org/download/libelf.so.1(ELFUTILS_1.0)

**Comment by probonopd** [comment]
Correction: I meant "We don't want to make libappimage depend on __libelfutil__, do we?"
The web of dependencies is getting complex...

**Comment by azubieta** [comment]
@probonopd as most of the functions listed above are already provided by libelf, there will be no need. I opened this issue just for information and discussion purposes. I do think that there is no need of migrating them to `libelfutil`.

Therefore I will close this issue.
Feel free to reopen it if you think there is something missing to say here :smile:
